// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHvmJEKzJJMJeSThTs8NsSbx2Zmm4L3M8',
    appId: '1:1073917965870:web:c75d410120c57ac37b91bf',
    messagingSenderId: '1073917965870',
    projectId: 'sh-samsarah',
    authDomain: 'sh-samsarah.firebaseapp.com',
    storageBucket: 'sh-samsarah.appspot.com',
    measurementId: 'G-3QKBQ6WERC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6AUr8R0WSSfTXCoASIVejthhGMxWQcJw',
    appId: '1:1073917965870:android:19b38225799661157b91bf',
    messagingSenderId: '1073917965870',
    projectId: 'sh-samsarah',
    storageBucket: 'sh-samsarah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW9Y3SFYm7d3kmQE_7syjmv_CxObLNbVY',
    appId: '1:1073917965870:ios:721f688d4c7abfce7b91bf',
    messagingSenderId: '1073917965870',
    projectId: 'sh-samsarah',
    storageBucket: 'sh-samsarah.appspot.com',
    iosClientId: '1073917965870-lrf1ffgjhvr1fgeq026oa76j8s4r9tcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.samsarah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW9Y3SFYm7d3kmQE_7syjmv_CxObLNbVY',
    appId: '1:1073917965870:ios:662b1ca43a766ea37b91bf',
    messagingSenderId: '1073917965870',
    projectId: 'sh-samsarah',
    storageBucket: 'sh-samsarah.appspot.com',
    iosClientId: '1073917965870-s4kcat205pmo9c89549t2d540o9n2006.apps.googleusercontent.com',
    iosBundleId: 'com.example.samsarah.RunnerTests',
  );
}
